global:
  scrape_interval:     15s # Scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['localhost:8000','127.0.0.1:5000']
